### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by Sparebola** [k1zn/RakBot#1]
**Пояснение `getBotState`**
Возвращает:
0 = "Подключение"
1 = "Пешеход"
2 = "Водитель"
3 = "Пассажир"
4 = "Наблюдатель"
5 = "Садится в машину"

**Пометка `bitStreamReset`**
После длительного использования ломает скрипт, лучше удалять через `bitStreamDelete`

**Пометка `getReconnectDelay`**
Возвращает кол-во мсек из конфига (+ 500 мсек)

**Пометка `openUrl`**
Отправляет запросы с сетевого адаптера, указанного в custom.ini

**Пояснение `disconnect`**
Аргумент bool, true - с таймаутом, false - без
Возможны краши

**Пометка `reconnect`, `defCallAdd`, `defCallDelete`**
Возможны краши

**Пометка `sendPickup`**
"Отправляет серверу информацию о поднятии пикапа" и телепортирует бота к нему

**Пометка `onTextLabelShow`**
Приходят не все лабелы, по неизвестной мне причине

**Пометка `onChatMessage`**
Приходят не все сообщения, по неизвестной мне причине

**Comment by k1zn** [comment]
Добавил все пометки, кроме "возможны краши" и "приходят не все лабелы". Это не гарантированная информация, такое я добавлять не буду.
